# Build, package, and publish a container image to our supported
# image registries. We generate a number of tags in different scenarios.
#
# * Commit pushed on default branch: publish with semver and "latest" tags.
# * Tag on default branch pushed: publish with short commit sha and "edge" tags.
#
# We currently publish to dockerhub and ghcr.

name: Package and publish container image

on:
  push:
    branches:
      - master
    tags:
      - "v*"

permissions:
  contents: read

jobs:
  publish:
    name: Build and publish image
    runs-on: ubuntu-22.04
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Generate container image meta tags
        id: meta
        uses: docker/metadata-action@818d4b7b91585d195f67373fd9cb0332e31a7175 # v4.6.0
        with:
          images: |
            statsd/statsd
            ghcr.io/statsd/statsd
          flavor: |
            latest=true
          tags: |
            type=semver,pattern=v{{version}},event=tag
            type=semver,pattern=v{{major}}.{{minor}},event=tag
            type=semver,pattern=v{{major}},event=tag
            type=edge,branch=$repo.default_branch,event=push
            type=sha,branch=$repo.default_branch,event=push

      - name: Setup buildx
        uses: docker/setup-buildx-action@f211e3e9ded2d9377c8cadc4489a4e38014bc4c9 # v1.7.0

      - name: Login to DockerHub container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub container registry
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Build and publish image
        id: docker_build
        uses: docker/build-push-action@0a97817b6ade9f46837855d676c4cca3a2471fc9 # v4.2.1
        with:
          push: true
          platforms: linux/amd64,linux/s390x,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}

      - name: Echo image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
